siteTitle = 'Face Tech'
siteDescr = 'Tân trang homestay'
siteDescription = "Tổng hợp những món đồ mà mình cần trong cuộc sống và công việc để khi đủ tiền thì rinh món đồ đó về nhà"
siteUrl = "https://facemmo.com/"
siteBandcampUrl = 'https://facemmo.com/'
siteMenuOne = 'Tham Quan'
siteMenuTwo = 'Ăn Uống'
siteMenuThree = 'Quan tâm'
siteAddress = 'WELCOME TO MY WEBSITE'
siteAddress2 = ''
sitePhone = '0899150055'
sitePhoneLink = 'tel:+84-089-915-0055'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
